name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker:
    name: Docker Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create git_hash File
        run: |
          set -Eeuo pipefail # fail fast: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
          printf "Hash,Branch,BuildTime\n%s,%s,%s" "`git rev-parse HEAD`" "`git rev-parse --abbrev-ref HEAD`" "`date -u`" > git_hash.txt

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: docker build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: gary.b.eengr_private
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY/go_web_dev:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY/go_web_dev:$IMAGE_TAG
