name: Docker Image CI

on:
  push:

# jobs:
#   build:
#     name: Docker Build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3.1.0
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
jobs:
  docker:
    name: Docker Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0


      - name: Create git_hash File
        run: |
          set -Eeuo pipefail # fail fast: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
          printf "Hash,Branch,BuildTime\n%s,%s,%s" "`git rev-parse HEAD`" "`git rev-parse --abbrev-ref HEAD`" "`date -u`" > git_hash.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
